Fix init script

diff --git a/net-misc/fiche/files/fiche.initd b/net-misc/fiche/files/fiche.initd
--- a/net-misc/fiche/files/fiche.initd
+++ b/net-misc/fiche/files/fiche.initd
@@ -5,7 +5,6 @@
 DAEMON="/usr/bin/${RC_SVCNAME}"
 PID_DIR=${PID_DIR:-/var/run/${RC_SVCNAME}}
 PID_FILE=${PID_DIR}/${RC_SVCNAME}.pid
-CONF_FILE="/etc/conf.d/${RC_SVCNAME}"
 USER=${RC_SVCNAME}
 GROUP=${RC_SVCNAME}
 
@@ -19,44 +18,37 @@ checkconfig() {
 		checkpath -q -d -o ${USER}:${GROUP} -m 0755 ${PID_DIR} || return 1
 	fi
 
-	if [ ! -f ${CONF_FILE} ]; then
-		eerror "Configuration file ${CONF_FILE} not found"
+	## /etc/conf.d/fiche: config file for /etc/init.d/fiche
+	## (!!!) Most important is providing DOMAIN and BASEDIR
+	[[ -n "${DOMAIN}" && ( -n "${BASEDIR}" && -d "${BASEDIR}" ) ]] && DAEMON_ARGS="-d ${DOMAIN} -o ${BASEDIR} " || {
+		eerror "You are not use DOMAIN or BASEDIR is not found..."
+		eerror "Please, see configuration file: /etc/conf.d/${RC_SVCNAME}."
 		return 1
-	else
-		## include config
-		. ${CONF_FILE}
-
-		## (!!!) Most important is providing DOMAIN and BASEDIR
-		[[ -n "${DOMAIN}" && ( -n "${BASEDIR}" && -d "${BASEDIR}" ) ]] && DAEMON_ARGS="-d ${DOMAIN} -o ${BASEDIR} " || {
-			eerror "You're is not use DOMAIN or BASEDIR is not found"
-			eerror "Please, see configuration file: /etc/conf.d/${RC_SVCNAME}."
-			return 1
+	}
+	[ -z "${PORT}" ] || DAEMON_ARGS+="-p ${PORT} "
+	[ -z "${WHILE_LIST}" ] || {
+		[ -f "${WHILE_LIST}" ] && DAEMON_ARGS+="-w ${WHILE_LIST} " || {
+			touch "${WHILE_LIST}" > /dev/null && chown ${USER}:${GROUP} "${WHILE_LIST}" || \
+				( eerror "Cannot create: ${WHILE_LIST}" && return 1 )
+			DAEMON_ARGS+="-w ${WHILE_LIST} "
 		}
-		[ -z "${PORT}" ] || DAEMON_ARGS+="-p ${PORT} "
-		[ -z "${WHILE_LIST}" ] || {
-			[ -f "${WHILE_LIST}" ] && DAEMON_ARGS+="-w ${WHILE_LIST} " || {
-				touch "${WHILE_LIST}" > /dev/null && chown ${USER}:${GROUP} "${WHILE_LIST}" || \
-					( eerror "Cannot create: ${WHILE_LIST}" && return 1 )
-				DAEMON_ARGS+="-w ${WHILE_LIST} "
-			}
+	}
+	[ -z "${BAN_LIST}" ] || {
+		[ -f "${BAN_LIST}" ] && DAEMON_ARGS+="-b ${BAN_LIST} " || {
+			touch "${BAN_LIST}" > /dev/null && chown ${USER}:${GROUP} "${BAN_LIST}" || \
+				( eerror "Cannot create: ${BAN_LIST}" && return 1 )
+			DAEMON_ARGS+="-b ${BAN_LIST} "
 		}
-		[ -z "${BAN_LIST}" ] || {
-			[ -f "${BAN_LIST}" ] && DAEMON_ARGS+="-b ${BAN_LIST} " || {
-				touch "${BAN_LIST}" > /dev/null && chown ${USER}:${GROUP} "${BAN_LIST}" || \
-					( eerror "Cannot create: ${BAN_LIST}" && return 1 )
-				DAEMON_ARGS+="-b ${BAN_LIST} "
-			}
+	}
+	[ -z "${SLUG_SIZE}" ] || DAEMON_ARGS+="-s ${SLUG_SIZE} "
+	[ -z "${BUFFER_SIZE}" ] || DAEMON_ARGS+="-B ${BUFFER_SIZE} "
+	[ -z "${LOGFILE}" ] || {
+		[ -f "${LOGFILE}" ] && DAEMON_ARGS+="-l ${LOGFILE} " || {
+			touch "${LOGFILE}" > /dev/null && chown ${USER}:${GROUP} "${LOGFILE}" || \
+				( eerror "Cannot create: ${LOGFILE}" && return 1 )
+			DAEMON_ARGS+="-l ${LOGFILE} "
 		}
-		[ -z "${SLUG_SIZE}" ] || DAEMON_ARGS+="-s ${SLUG_SIZE} "
-		[ -z "${BUFFER_SIZE}" ] || DAEMON_ARGS+="-B ${BUFFER_SIZE} "
-		[ -z "${LOGFILE}" ] || {
-			[ -f "${LOGFILE}" ] && DAEMON_ARGS+="-l ${LOGFILE} " || {
-				touch "${LOGFILE}" > /dev/null && chown ${USER}:${GROUP} "${LOGFILE}" || \
-						( eerror "Cannot create: ${LOGFILE}" && return 1 )
-				DAEMON_ARGS+="-l ${LOGFILE} "
-			}
-		}
-	fi
+	}
 }
 
 start() {
